#
# The groups that we will rank up to
RankGroups: [New, Member, Citizen, Veteran, Legendary]

#
# The time it takes to rank up to one of the groups in RankGroups
AfterHours: [0, 2, 24, 96, 1000]

#
# A player that is able to rank up will be reminded every elapsed time span
RemindAfterTimeSpan: 10

eithon:
  UseMarkUpForMessages: 0
  UseWrappingForMessages: 0
  
  #
  # Debug level
  #  0 = NONE (no debug messages)
  #  1 = MAJOR (only major messages)
  #  2 = MINOR (also minor messages)
  #  3 = VERBOSE (all messages)
  #
  DebugLevel: 1

messages:

  #
  # Parameters: <playtime in hours>(%d)
  PlayTime_1: You have played %d hours.

  #
  # Parameters: <group name>(%s)
  RankedUpToGroup_1: You have been ranked up to group %s!

  #
  # Parameters: <hours remaining>(%d) <next rank>(%s)
  TimeToNextRank_2: You have %d hours left to rank %s.

  #
  # Parameters: <higest rank>(%s)
  ReachedHighestRank_1: You have reached the highest rank, %s!

  #
  # Parameters: NONE
  NotEligibleForRankUp_0: You are not eligible for rank up.

  #
  # Parameters: <next rank>(%s)
  RememberToRankUp_1: You are now eligible for rank up to %s.

