#
# The groups that we will rank up to
RankGroups: [New, Member, Citizen, Veteran, Legendary]

#
# The time it takes to rank up to one of the groups in RankGroups
AfterHours: [0, 1, 24, 96, 1000]

#
# A player that is able to rank up will be reminded every elapsed time span
RemindAfterTimeSpan: 10

eithon:
  UseMarkUpForMessages: 1
  UseWrappingForMessages: 0
  
  #
  # Debug level
  #  0 = NONE (no debug messages)
  #  1 = MAJOR (only major messages)
  #  2 = MINOR (also minor messages)
  #  3 = VERBOSE (all messages)
  #
  DebugLevel: 1

messages:

  #
  # Parameters: <time span>(%s)
  PlayTime_1: You have played for %s..

  #
  # Parameters: <group name>(%s)
  RankedUpToGroup_1: You have been ranked up to group %s!

  #
  # Parameters: <next rank>(%s), <timespan>(%s)
  TimeToNextRank_2: You will reach next rank (%s) in %s.

  #
  # Parameters: <higest rank>(%s)
  ReachedHighestRank_1: You have reached the highest rank, %s!

  #
  # Parameters: NONE
  NotEligibleForRankUp_0: Your rank is not eligible for rank up. 

  #
  # Parameters: <next rank>(%s)
  RememberToRankUp_1: You are now eligible for rank up to %s. ([color=aqua]/rankup[/color])

