name: EithonRankUp
main: net.eithon.plugin.rankup.Plugin
version: 1.0.
author: vanbrayne
depend: [EithonLibrary]
softdepend: [zPermissions, Oracle]
description: A Minecraft plugin for RankUp
commands:
  rankup:
    description: Rank up a player based on play time
    usage: /rankup
    permission-message: You don't have <permission>
permissions:
  rankup.*:
    description: Gives access to all rankup commands
    default: op
    rankup.staff: true
  rankup.staff:
    description: No rankup for staff
    default: op
