name: EithonRankUp
main: net.eithon.plugin.rankup.Plugin
version: 1.4.3
author: vanbrayne
depend: [EithonLibrary, zPermissions]
softdepend: [EithonStats]
description: A Minecraft plugin for RankUp
commands:
  rankup:
    description: Rank up a player based on play time
    usage: /rankup
    permission-message: You don't have <permission>
permissions:
  rankup.*:
    description: Gives access to all rankup commands
    default: op
    rankup.staff: true
  rankup.noteligible:
    description: No rankup for some
    default: op
